- name: Create a directory if it does not exist
  file:
    path: /home/ubuntu
    state: directory

- name: Extract artifact
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "start server"
  become: true
  shell: |
    cd /home/ubuntu
    npm install
    pm2 stop default
    pm2 start npm -- start